### ISSUE TITLE
Capping time spent searching

### ISSUE THREAD

**Issue by mhughson** [roy-t/AStar#14]
Is there a good way to handle unreachable points? It appears that there is no way to early out of your path search, so an unreachable point will be very, **very**, expensive.

I would like a way to tell the GetPath function to exit early after either visiting N number of nodes, or after spending N amount of time. This way I can avoid huge hangs when an invalid search is requested.

This may have some overlap with https://github.com/roy-t/AStar/issues/10

**Comment by roy-t** [comment]
This feature was added in version 2.1.0, which should be available now on NuGet. Check the new GetPath overload. Note that I implemented this by duplicating a tiny bit of code. So the check does not effect the version that does not have an interationLimit.

**Comment by mhughson** [comment]
Tested and works, but slightly different than I expected. I was expecting that in a failure case (eg. when it hits the IterationLimit) it would return the "best" path it had found so far. Maybe returning PartiallyReconstructPath(grid, start, current, cameFrom); instead of null? I suppose it should also communicate that the path returned is not the full path (an out bool param?).

**Comment by cclogg** [comment]
Good discussion along with #10. I guess I'll add my comment here to this post. The general idea of 'best' path, from what I can tell, is taking the node that had the lowest H score in the case of no full path found. I just made some changes on my end to test this out and I think it works.
1. In Grid.cs, "GetPath" becomes:
```
public Position[] GetPath(Position start, Position end, Offset[] movementPattern, int iterationLimit, out bool fullPathNotFound)
{
        var current = PathFinder.FindPath(this, start, end, movementPattern, iterationLimit, out fullPathNotFound);
        [...]
}
```
2. In Pathfinder.cs "FindPath" method becomes:
```
public static List<Position> FindPath(Grid grid, Position start, Position end, Offset[] movementPattern, int iterationLimit, out bool fullPathNotFound)
{
            ClearStepList();

            fullPathNotFound = false;

            if (start == end)
            {
                return new List<Position> { start };
            }

            var head = new MinHeapNode(start, ManhattanDistance(start, end));
            MinHeapNode lowestHNode = head;
            var open = new MinHeap();
            open.Push(head);

            var costSoFar = new float[grid.DimX * grid.DimY];
            var cameFrom = new Position[grid.DimX * grid.DimY];
            
            while (open.HasNext() && iterationLimit > 0)
            {
                // Get the best candidate
                var currentNode = open.Pop();
                var current = currentNode.Position;
                MessageCurrent(current, PartiallyReconstructPath(grid, start, current, cameFrom));
                if (currentNode.ExpectedCost < lowestHNode.ExpectedCost)
                    lowestHNode = currentNode;
                if (current == end)
                {
                    return ReconstructPath(grid, start, end, cameFrom);
                }

                Step(grid, open, cameFrom, costSoFar, movementPattern, current, end);

                MessageClose(current);

                --iterationLimit;
            }

            fullPathNotFound = true;
            return ReconstructPath(grid, start, lowestHNode.Position, cameFrom);

            //return null;
        }
```
Also in my project, if the path kept coming back with "fullPathNotFound==true" (ie 2 in a row), then I would tell the unit to do something else, since obviously it can't make it to whatever it is trying to.
