### ISSUE TITLE
Prevent cutting corners

### ISSUE THREAD

**Issue by Dan-Matt** [roy-t/AStar#16]
This isn't really an issue, it's more of a feature. I was having a problem in that the path will cut corners instead of finding the way around. This is probably standard A* behaviour but I needed it to work a bit differently for a game I'm working on. I forked the code and made the change.
https://github.com/EnderYoss/AStar/commit/c1633de8f2315c581e2005ab0e994151cecaf661

I just thought I'd let you know in case you wanted to use it or adapt it. The difference can be seen here-
![astardiagram](https://user-images.githubusercontent.com/13627211/38392972-35922d80-3921-11e8-9dea-8228df94954c.png)

**Comment by EnderYoss** [comment]
Just to reiterate - I don't mind if you include this feature or not I just wanted to make you aware of it! Thanks

**Comment by roy-t** [comment]
Ah I actually had a 'cutCorners' option in a really old A* version (https://roy-t.nl/2009/02/24/implementing-a-path-finding-in-c-and-xna-source-code-can-we-cut-the-corner.html). I didn't implement that option in the new version yet. I think the way you've done it, only checking late is pretty smart. I'm not sure if I want to integrate it yet. But I'll keep this ticket open. 

Thanks a lot!

**Comment by roy-t** [comment]
I've thought of another option that might solve this. See #18, no ETA though :)

**Comment by Dan-Matt** [comment]
Sweet sounds good I'll be following this!

**Comment by rallianto** [comment]
> 
> 
> This isn't really an issue, it's more of a feature. I was having a problem in that the path will cut corners instead of finding the way around. This is probably standard A* behaviour but I needed it to work a bit differently for a game I'm working on. I forked the code and made the change.
> [Dan-Matt@c1633de](https://github.com/Dan-Matt/AStar/commit/c1633de8f2315c581e2005ab0e994151cecaf661)
> 
> I just thought I'd let you know in case you wanted to use it or adapt it. The difference can be seen here-
> ![astardiagram](https://user-images.githubusercontent.com/13627211/38392972-35922d80-3921-11e8-9dea-8228df94954c.png)

How did you achieve that I am interested to know?
