### ISSUE TITLE
the edge of the bolck can only go straight. What should I do?

### ISSUE THREAD

**Issue by ruijiexie** [roy-t/AStar#19]
With MovementPatterns.Full, the edge of the bolck can only go straight. eg. if (x,y) is block, can't move (x-1, y) to (x+1, y-1) . What should I do?

**Comment by roy-t** [comment]
Hey,

I'm sorry I don't understand. Can you take a screenshot in the editor when this problem occurs?

**Comment by ruijiexie** [comment]
//var cellCost = grid.GetCellCostUnchecked(position);
var cellCost = grid.GetCellCostUnchecked(current, option);

        internal float GetCellCostUnchecked(Position current, Offset option)
        {
            if (Array.IndexOf(MovementPatterns.DiagonalOnly, option) == -1)
            {
                return GetCellCostUnchecked(current + option);
            }
            else
            {
                var posx = current + new Offset(option.X, 0);
                var posy = current + new Offset(0, option.Y);

                if (float.IsInfinity(GetCellCostUnchecked(posx)))
                    return float.PositiveInfinity;

                if (float.IsInfinity(GetCellCostUnchecked(posy)))
                    return float.PositiveInfinity;

                return GetCellCostUnchecked(current + option);
            }
        }
I modified the code so that I won’t stick to the wall when I walk.
