### ISSUE TITLE
Info: v2 WIP version available on Master

### ISSUE THREAD

**Issue by roy-t** [roy-t/AStar#31]
A WIP version of v2 is now on master. It includes
- Graph based path finding
- Partial paths

It also uses actual numbers to feed the algorithm. So a node has a position, and an edge has a max speed at which you can traverse it. So if two nodes are connected by an edge and are 120km a part, and the edge has a speed limit of 60km/h, the cost of traveling between these two nodes is 2 hours. This will hopefully make it easier for the end-user to construct graphs that work well for the real world.

As of yet the v2 version only supports graphs, while v1 only supports grids. I'm thinking of clever and fast ways to marry the two, with an interface that looks similar to v1. But in the end it might be simpler to have two different approaches. Who knows :).

V2 also contains a brand new viewer, which is also very much WIP:
![Capture](https://user-images.githubusercontent.com/623634/72907630-75131500-3d34-11ea-9df5-9daf223d662f.PNG)

**Comment by bradzoob** [comment]
Glorious work!

**Comment by roy-t** [comment]
And released 💃
