### ISSUE TITLE
Hidden Connect method

### ISSUE THREAD

**Issue by backmari** [roy-t/AStar#32]
In the usage examples for graphs, node connections are added like this:

    nodeA.Connect(nodeB, traversalVelocity);

However, since commit 1daf2de8a9ae0834fc587bebdc3884c2cf344b95 the Connect method is internal. How are node connections to be added now?

**Comment by roy-t** [comment]
Ah that's a stupid oversight from me. I at one point intended to use the concrete node and edge classes inside a larger `Graph` class that would do all the work for you internally. Just like the `Grid` class does. But I did not get around to it yet. In the mean time I forgot to make the connect method available again. I'll update the source code and package next Wednesday! Thanks for creating the issue!

**Comment by roy-t** [comment]
I found some time, I've upload versions 3.0.1 which fixes this issue :). It should be available in a few minutes. https://www.nuget.org/packages/RoyT.AStar/3.0.1

**Comment by backmari** [comment]
@roy-t Great, thanks!
