### ISSUE TITLE
Isometric Support

### ISSUE THREAD

**Issue by JoNMii** [roy-t/AStar#34]
Hi,
Thanks for your lib. My grid is isometric and rotated so i cant define a new Grid(600,600) for example.
In my Grid Y axis goes from -300 to 300 and X axis from 0 to 600.

Im trying to add AStar on a isometric grid, to move in 8 directions. 
Thanks

**Comment by roy-t** [comment]
Hey @JoNMii ,

You can easily create a grid where you can move in 8 directions by using `Grid.CreateGridWithLateralAndDiagonalConnections(..);`. 

Also keep in mind that the grid used in this library, is for path finding only. It is an abstract representation of your game world. So you don't have to rotate the path finding grid, or have to have it go from -300 to 300. You need to do is establish a mapping from a cell in your world grid, to a cell in your path finding grid, and back. 

Does this help?
