### ISSUE TITLE
Coming to v3

### ISSUE THREAD

**Issue by cortaninha** [roy-t/AStar#35]
Hello thank you for your work.
I've been using an old version but now moved to 3.01.
Can you explain how to do the same functionality that existed with BlockCell and UnblockCell ?

I have been using those functions to make grid nodes walkable/non walkable in my game but in the new version these functions are not there. Only can find DisconnectNode. How to reconnect?

**Comment by roy-t** [comment]
Hey @cortaninha,

Ah you can use the GetNode function to get the nodes you want and then connect them again using Node.Connect. If you want more control you can also use all the nodes and edge classes.

**Comment by cortaninha** [comment]
Thank you for your quick response.
One question about the Node.Connect, do i have to connect to all adjacent nodes for the pathing to work again for that node? I dont want to recalculate the grid every time some building is destroyed.

**Comment by roy-t** [comment]
Hey,

Yes you have to reconnect to all nodes that you would like a connection to (so all surrounding nodes).

I don't really understand "I don't want to recalculate the grid every time some building is destroyed." You can just create a helper function to connect it to all 'neighbors' for you. Its not an expensive operation.
