### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MAYasin** [roy-t/AStar#45]
Just a question, would like to know how to convert the edges to a position like a coordinate system (X, Y). I am working on a game that uses angles as a direction (the map is like a graph) that my player uses to move. Having the position of the edges would be really helpful.
Should I create more nodes to store my obstacles?
Sample code usage of this library would be really helpful.

**Comment by roy-t** [comment]
Hey MAYasin, 

I'm not sure if I follow. Each node has a position property which gives the position of the node. Or are you using the Grid class to generate a grid of connected nodes? In that case you should map the 'abstract' location of a node (for example {1, 1}) to a physical location like,  New York or {1254.42f, 41.2f} in your own code using a mapping function. 

Alternatively you can also generate the nodes yourself so you can use the position property.

You can take a look at the viewer or the tests if you want more sample code to study the library.

Does that help? (Closing for now, please re-open if you have more questions)
