### ISSUE TITLE
Question: obstacles

### ISSUE THREAD

**Issue by JamesPurvis** [roy-t/AStar#49]
Hello,

This is probably a stupid question, but I have a project I'm working on where the grid obstacles change often and the grid map is shared with multiple agents. I don't want my agents to be able to walk through each other, so I need to be able to update my grid easily. I see there is an option to disconnect a node, which seems to make the position on the grid unusable, but is there anyway to add the same node back after you remove it?

**Comment by roy-t** [comment]
Hey James,

You can use the [Grid.AddEdge](https://github.com/roy-t/AStar/blob/master/Roy-T.AStar/Grids/Grid.cs#L250) method to add a connection between two points again :).

**Comment by JamesPurvis** [comment]
Wow! How didn't I see that thanks so much

**Comment by roy-t** [comment]
Haha it happens, no worries!
________________________________
